import React from "react"
import { Button } from "./button"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Button,
  "https://www.figma.com/design/YOUR_FILE_KEY?node-id=YOUR_NODE_ID",
  {
    props: {
      variant: figma.enum("Variant", {
        Default: "default",
        Destructive: "destructive",
        Outline: "outline",
        Secondary: "secondary",
        Ghost: "ghost",
        Link: "link",
      }),
      size: figma.enum("Size", {
        Default: "default",
        Small: "sm",
        Large: "lg",
        Icon: "icon",
      }),
      asChild: figma.boolean("As Child", {
        true: true,
        false: false,
      }),
    },
    example: ({ variant, size, asChild }) => (
      <Button variant={variant} size={size} asChild={asChild}>
        Button
      </Button>
    ),
  }
)

