import React from "react"
import {
  Dialog,
  DialogTrigger,
  DialogContent,
  DialogHeader,
  DialogFooter,
  DialogTitle,
  DialogDescription,
} from "./dialog"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * Replace YOUR_FIGMA_URL with your actual Figma component URL
 */

// Dialog component
figma.connect(
  Dialog,
  "YOUR_FIGMA_URL", // Replace with: https://www.figma.com/design/...?node-id=...
  {
    props: {
      open: figma.boolean("Open"),
      children: figma.children(["DialogTrigger", "DialogContent"]),
    },
    example: ({ open, children }) => (
      <Dialog open={open}>
        {children}
      </Dialog>
    ),
  },
)

// DialogContent
figma.connect(
  DialogContent,
  "YOUR_FIGMA_URL_CONTENT", // Replace with DialogContent node-id
  {
    props: {
      children: figma.children(["DialogHeader", "DialogFooter"]),
    },
    example: ({ children }) => (
      <DialogContent>
        {children}
      </DialogContent>
    ),
  },
)

// DialogHeader
figma.connect(
  DialogHeader,
  "YOUR_FIGMA_URL_HEADER", // Replace with DialogHeader node-id
  {
    props: {
      children: figma.children(["DialogTitle", "DialogDescription"]),
    },
    example: ({ children }) => (
      <DialogHeader>
        {children}
      </DialogHeader>
    ),
  },
)

// DialogTitle
figma.connect(
  DialogTitle,
  "YOUR_FIGMA_URL_TITLE", // Replace with DialogTitle node-id
  {
    props: {
      children: figma.children("*"),
    },
    example: ({ children }) => (
      <DialogTitle>{children}</DialogTitle>
    ),
  },
)

// DialogDescription
figma.connect(
  DialogDescription,
  "YOUR_FIGMA_URL_DESCRIPTION", // Replace with DialogDescription node-id
  {
    props: {
      children: figma.children("*"),
    },
    example: ({ children }) => (
      <DialogDescription>{children}</DialogDescription>
    ),
  },
)

// DialogFooter
figma.connect(
  DialogFooter,
  "YOUR_FIGMA_URL_FOOTER", // Replace with DialogFooter node-id
  {
    props: {
      children: figma.children("*"),
    },
    example: ({ children }) => (
      <DialogFooter>{children}</DialogFooter>
    ),
  },
)

