import React from "react"
import { Input } from "./input"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * Replace YOUR_FIGMA_URL with your actual Figma component URL
 */

figma.connect(
  Input,
  "YOUR_FIGMA_URL", // Replace with: https://www.figma.com/design/...?node-id=...
  {
    props: {
      // Input type
      type: figma.enum("Type", {
        Text: "text",
        Email: "email",
        Password: "password",
        Number: "number",
        Tel: "tel",
        URL: "url",
        Search: "search",
        Date: "date",
      }),
      // Placeholder text
      placeholder: figma.string("Placeholder"),
      // Disabled state
      disabled: figma.boolean("Disabled"),
      // Required validation
      required: figma.boolean("Required"),
      // Read-only state
      readOnly: figma.boolean("ReadOnly"),
    },
    example: ({ type, placeholder, disabled, required, readOnly }) => (
      <Input
        type={type}
        placeholder={placeholder}
        disabled={disabled}
        required={required}
        readOnly={readOnly}
      />
    ),
  },
)

